<x-app-layout>
    <div class="space-y-8">
        {{-- Header Section --}}
        <div class="relative bg-zinc-900 border border-zinc-800 rounded-2xl p-8 overflow-hidden">
            <div class="absolute inset-0 bg-gradient-to-br from-indigo-500/10 via-zinc-900/50 to-purple-500/10 opacity-50"></div>
            <div class="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                <div>
                    <h1 class="text-3xl font-bold text-white tracking-tight">{{ __('Revenue & Invoices') }}</h1>
                    <p class="mt-2 text-zinc-400 max-w-2xl">
                        {{ __('Track all financial transactions and invoices generated by the system.') }}
                    </p>
                </div>
                <a href="{{ route('admin.revenue.export') }}" class="inline-flex items-center px-4 py-2 bg-zinc-800 border border-zinc-700 rounded-xl font-semibold text-xs text-zinc-300 uppercase tracking-widest hover:bg-zinc-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-zinc-900 transition-all shadow-lg">
                    <svg class="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    {{ __('Export CSV') }}
                </a>
            </div>
        </div>

        {{-- Stats Cards --}}
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 relative overflow-hidden group">
                <div class="absolute inset-0 bg-gradient-to-br from-emerald-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                <div class="relative z-10">
                    <p class="text-sm font-medium text-zinc-400 uppercase tracking-wider">Total Revenue (Lifetime)</p>
                    <p class="mt-2 text-3xl font-bold text-white overflow-hidden text-ellipsis">
                        ${{ number_format($totalRevenue, 2) }}
                    </p>
                </div>
                <div class="absolute top-6 right-6 p-3 bg-emerald-500/10 rounded-xl text-emerald-500">
                    <svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
            </div>

            <div class="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 relative overflow-hidden group">
                <div class="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
                <div class="relative z-10">
                    <p class="text-sm font-medium text-zinc-400 uppercase tracking-wider">This Month's Revenue</p>
                    <p class="mt-2 text-3xl font-bold text-white overflow-hidden text-ellipsis">
                        ${{ number_format($monthlyRevenue, 2) }}
                    </p>
                </div>
                <div class="absolute top-6 right-6 p-3 bg-indigo-500/10 rounded-xl text-indigo-500">
                    <svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                    </svg>
                </div>
            </div>
        </div>

        {{-- Transactions Table --}}
        <div class="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden shadow-xl">
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-zinc-800">
                    <thead class="bg-zinc-900/50">
                        <tr>
                            <th scope="col" class="px-6 py-4 text-left text-xs font-medium text-zinc-400 uppercase tracking-wider">User</th>
                            <th scope="col" class="px-6 py-4 text-left text-xs font-medium text-zinc-400 uppercase tracking-wider">Description</th>
                            <th scope="col" class="px-6 py-4 text-left text-xs font-medium text-zinc-400 uppercase tracking-wider">Amount</th>
                            <th scope="col" class="px-6 py-4 text-left text-xs font-medium text-zinc-400 uppercase tracking-wider">Status</th>
                            <th scope="col" class="px-6 py-4 text-left text-xs font-medium text-zinc-400 uppercase tracking-wider">Date</th>
                            <th scope="col" class="px-6 py-4 text-left text-xs font-medium text-zinc-400 uppercase tracking-wider">Invoice ID</th>
                            <th scope="col" class="px-6 py-4 text-right text-xs font-medium text-zinc-400 uppercase tracking-wider">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-zinc-800 bg-zinc-900">
                        @forelse($transactions as $transaction)
                            <tr class="hover:bg-zinc-800/50 transition-colors">
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center">
                                        <div class="flex-shrink-0 h-10 w-10">
                                            <img class="h-10 w-10 rounded-full object-cover ring-2 ring-zinc-800" 
                                                 src="{{ $transaction->user->profile_picture ? Storage::url($transaction->user->profile_picture) : 'https://ui-avatars.com/api/?name='.urlencode($transaction->user->name).'&background=6366f1&color=fff' }}" 
                                                 alt="{{ $transaction->user->name }}">
                                        </div>
                                        <div class="ml-4">
                                            <div class="text-sm font-medium text-white">
                                                <a href="{{ route('admin.users.edit', $transaction->user) }}" class="hover:text-indigo-400 hover:underline">
                                                    {{ $transaction->user->name }}
                                                </a>
                                            </div>
                                            <div class="text-sm text-zinc-500">{{ $transaction->user->email }}</div>
                                        </div>
                                    </div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-zinc-300">{{ $transaction->description ?? '-' }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <div class="text-sm text-white font-mono">{{ $transaction->currency }} {{ number_format($transaction->amount, 2) }}</div>
                                    <div class="text-xs text-zinc-500">{{ ucfirst($transaction->payment_method ?? 'card') }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    @php
                                        $statusColors = [
                                            'paid' => 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
                                            'open' => 'bg-blue-500/10 text-blue-500 border-blue-500/20',
                                            'pending' => 'bg-amber-500/10 text-amber-500 border-amber-500/20',
                                            'failed' => 'bg-red-500/10 text-red-500 border-red-500/20',
                                            'void' => 'bg-zinc-500/10 text-zinc-500 border-zinc-500/20',
                                            'uncollectible' => 'bg-red-500/10 text-red-500 border-red-500/20',
                                        ];
                                        $colorClass = $statusColors[$transaction->status] ?? 'bg-zinc-500/10 text-zinc-500 border-zinc-500/20';
                                    @endphp
                                    <span class="px-2.5 py-0.5 rounded-full text-xs font-medium border {{ $colorClass }}">
                                        {{ ucfirst($transaction->status) }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-zinc-400">
                                    {{ $transaction->paid_at ? $transaction->paid_at->format('M d, Y') : '-' }}
                                    <div class="text-xs text-zinc-600">{{ $transaction->paid_at ? $transaction->paid_at->format('h:i A') : '' }}</div>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-zinc-500 font-mono">
                                    {{ $transaction->invoice_id }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    @if($transaction->invoice_pdf_url)
                                        <a href="{{ $transaction->invoice_pdf_url }}" target="_blank" class="text-indigo-400 hover:text-indigo-300">Download PDF</a>
                                    @else
                                        <span class="text-zinc-600 cursor-not-allowed">N/A</span>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="px-6 py-12 text-center">
                                    <div class="mx-auto h-12 w-12 text-zinc-600">
                                        <svg class="h-12 w-12" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                        </svg>
                                    </div>
                                    <h3 class="mt-2 text-sm font-medium text-white">No transactions found</h3>
                                    <p class="mt-1 text-sm text-zinc-500">New transactions will appear here.</p>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            
            @if($transactions->hasPages())
                <div class="px-6 py-4 border-t border-zinc-800 bg-zinc-900/50">
                    {{ $transactions->links() }}
                </div>
            @endif
        </div>
    </div>
</x-app-layout>
